### ISSUE TITLE
shift-S no longer working after upgrade to v4.5.43 on TB 128.10.0esr

### ISSUE THREAD

**Issue by embeh** [opto/nostalgy-xpi#294]
This is on Thunderbird 128.10.0esr running on Windows 10.

I just upgraded "Manage Emails/Nostaqlgy++" extension to version 4.5.43 and now the hotkey "shift-S" is no longer working.
Normal hotkey "S" works.

When pressing shift-S, the error console reports: 

```
Uncaught TypeError: cmd is not a function
    NostalgySuggested chrome://nostalgy/content/nostalgy.js:1156
    NostalgyParseCommand chrome://nostalgy/content/nostalgy.js:1466
    onNostalgyKeyPress chrome://nostalgy/content/nostalgy.js:1448
nostalgy.js:1156:36
    NostalgySuggested chrome://nostalgy/content/nostalgy.js:1156
    NostalgyParseCommand chrome://nostalgy/content/nostalgy.js:1466
    onNostalgyKeyPress chrome://nostalgy/content/nostalgy.js:1448
```

shift-S is THE killer feature of Nostalgy for me 😄 so it is a bit sad to see this broken... 
I might have to downgrade to an older version of Nostalgy for now...

**Comment by embeh** [comment]
PS: Not sure this is related but when I open the Add-ons Manager while the Error Console is open, I do see lots of errors similar to this one:

```
Uncaught (in promise) Error: Error while loading 'jar:file:///C:/Users/username/AppData/Roaming/Thunderbird/Profiles/profilename/extensions/extensionname@publisher.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)
    readJSON resource://gre/modules/Extension.sys.mjs:1136
    onStopRequest resource://gre/modules/NetUtil.sys.mjs:124
2 Extension.sys.mjs:1136:20
```
This repeats for basically all extensions I have installed, just with different extension/publisher names

**Comment by embeh** [comment]
Manually installing version 4.5.33 fixed the issue.

**Comment by opto** [comment]
I forgot to test the shift command versions.

The update became necessary because the eval function is forbidden in the future- but stils works in 128.

I have set 4.5.43 for 137 and 138 only - there better than nothing - so TB will not try to update you again to 4.5.43 from 4.5.33

**Comment by embeh** [comment]
> I forgot to test the shift command versions.
> 
> The update became necessary because the eval function is forbidden in the future- but stils works in 128.
> 
> I have set 4.5.43 for 137 and 138 only - there better than nothing - so TB will not try to update you again to 4.5.43 from 4.5.33

Thanks for the update - will shift-S become available again in future releases?

**Comment by opto** [comment]
yes ... pretty soon, depends on review time

**Comment by Olifair** [comment]
I haven't found the 4.5.33 version here, but I tried to install the 4.5.38 on TB 128.10.0, but it tells me that it's not compatible. 
So I'm stuck with 4.5.43 ? 
@embeh  where did you find 4.5.33 and how did you manage to install it ?

**Comment by opto** [comment]
here: https://addons.thunderbird.net/de/thunderbird/addon/nostalgy_ng/versions/?page=1#version-4.5.33

extra addons nostalgy deinstall (under ...), then cog symbol install from file

**Comment by Olifair** [comment]
Thanks very much Klaus for your very rapid solution.
I actually did not have to deinstall the old version, but I had to restart TB to make it work :-)
And all shift- commands are back, and I'm very happy, as shift-S is what I use most. :-)

**Comment by embeh** [comment]
@opto beat me to it - https://addons.thunderbird.net/en-US/thunderbird/addon/nostalgy_ng/versions/ is where you can get older version, and yes I was able to directly install without deinstall (not to loose the history/statistics for shift-S).

**Comment by Olifair** [comment]
thanks @embeh . My problem actually was that you can also get older version on github : [https://github.com/opto/nostalgy-xpi/releases](https://github.com/opto/nostalgy-xpi/releases)  but for some strange reason not the 4.5.33 :-)

**Comment by opto** [comment]
github only gets the versions when review is slow .... so some are here,some on ATN

**Comment by staki1966** [comment]
Another possible workaround while Klaus is working on the fix: shift-B (move message to folder _and_ go to folder) does work. You still need to go back to the original folder, but I find this easier for my workflow than having to do lowercase-s and type the folder name manually. I almost always move messages from my primary inbox, and I can easily get to it (e.g. using the QuickFolders extension)

**Comment by opto** [comment]
you can also get to your inbox (or some other folder) by setting it as 'home' folder: rightclick on the folder  in the folder pane for that.

Then, there is a command Ctrl-Alt-j to go to the home folder. Change in extra-addons-cog symbol - keys

**Comment by staki1966** [comment]
This issue seems to be fixed in release 4.5.49. Thanks Klaus!
